### ISSUE TITLE
2.7.2 Manage Orders (Corporate) - Incorrect web page display on clicking "Give Review" button

### ISSUE THREAD

**Issue by Shreya-Guha** [Palspal98/FarmFree#2]
On clicking the "Give Review" button, the system gets redirected to a web page asking for Payment Details. @ryanreh99

**Comment by ryanreh99** [comment]
Pushed [c293fe](https://github.com/Palspal98/FarmFree/commit/c293fe0ecd978e9d397ac074d5b90362c407765c) to [80610](https://github.com/Palspal98/FarmFree/commit/806109bf22ad1377b6bbafd4213d77a4a18d02a5).

**Comment by Shreya-Guha** [comment]
On clicking the "Give Review" button, no web page is being displayed.   @ryanreh99

**Comment by ryanreh99** [comment]
This is expected behaviour.
**[ wontfix ]** - Page used only for testing MakePaymentUI.

**Comment by Shreya-Guha** [comment]
Issue closed as button non-existent in the latest version.
