### ISSUE TITLE
2.8 Make Payment - Accepting Incorrect details in "Name on Card" field

### ISSUE THREAD

**Issue by Shreya-Guha** [Palspal98/FarmFree#5]
Error: On entering numeric values in "Name on Card" field, the details are getting accepted which shouldn't be the case. @ryanreh99 

![Payment Name](https://user-images.githubusercontent.com/43537297/125053214-78ce5f00-e0c2-11eb-9233-013d58536589.png)

![Name_payment](https://user-images.githubusercontent.com/43537297/125053472-c5b23580-e0c2-11eb-9f67-eef74c38148f.png)

**Comment by ryanreh99** [comment]
This is expected behavior - works the same everywhere.

**Comment by Palspal98** [comment]
This is expected behaviour 
@rdutta1999 can you have a look into this

**Comment by rdutta1999** [comment]
No, I rather not.

**Comment by rdutta1999** [comment]
No, I rather not.

**Comment by Shreya-Guha** [comment]
It is noted that this is Stripe function, which was previously inadvertently overlooked. So this can now be ignored as this will be attended by a 3rd party.
